/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Patient;
import model.PatientDirectory;
import model.PersonDirectory;
//import model.PersonDirectory;

/**
 *
 * @author darsh
 */
public class adminPatient extends javax.swing.JFrame {


    public adminPatient(PersonDirectory perList, PatientDirectory patDirectory) {
    }

    /**
     * Creates new form adminPatient
     */
    //PersonDirectory perList;
    PatientDirectory patDirectory;
    
    
//    public adminPatient(PatientDirectory patDirectory) {
//        this(patDirectory);
//    }
//
//    public adminPatient(PatientDirectory patDirectory) {
//        this(patDirectory);
//    }
//
//    public adminPatient(PatientDirectory patDirectory) {
//        initComponents();
//        this.patDirectory = patDirectory;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnMedIns = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblMedIns = new javax.swing.JLabel();
        rbtnYes = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        lblAllergy = new javax.swing.JLabel();
        txtAllergy = new javax.swing.JTextField();
        lblSymptom = new javax.swing.JLabel();
        txtSymptom = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblHi = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMedIns.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMedIns.setText("Do you have Medical Insurance?");

        rbtnMedIns.add(rbtnYes);
        rbtnYes.setText("Yes");

        rbtnMedIns.add(rbtnNo);
        rbtnNo.setText("No");

        lblAllergy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAllergy.setText("Allergies");

        lblSymptom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSymptom.setText("Symptom");

        btnCreate.setText("Create Patient");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblHi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHi.setText("Hi,");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblHi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMedIns)
                    .addComponent(lblAllergy)
                    .addComponent(lblSymptom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSymptom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnNo))
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtAllergy))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAllergy, lblMedIns, lblSymptom});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHi))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedIns)
                    .addComponent(rbtnYes)
                    .addComponent(rbtnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAllergy)
                    .addComponent(txtAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSymptom)
                    .addComponent(txtSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        String allergy = txtAllergy.getText();
        String symptom = txtSymptom.getText();
        
        Patient p = patDirectory.addPatient();
        
        p.setAllergy(allergy);
        p.setSymptom(symptom);
        if(rbtnYes.isSelected()==true)
            {
                p.setGender("Yes");
            }
        if(rbtnNo.isSelected()==true)
            {
                p.setGender("No");
            }
        
        JOptionPane.showMessageDialog(this, "Patient Record Inserted..!!");
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAllergy;
    private javax.swing.JLabel lblHi;
    private javax.swing.JLabel lblMedIns;
    public javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblSymptom;
    private javax.swing.ButtonGroup rbtnMedIns;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnYes;
    private javax.swing.JTextField txtAllergy;
    private javax.swing.JTextField txtSymptom;
    // End of variables declaration//GEN-END:variables
}
