/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.table.DefaultTableModel;
import model.PatientDirectory;
import model.PersonDirectory;

/**
 *
 * @author darsh
 */
public class adminPatientVUS extends javax.swing.JPanel {

    /**
     * Creates new form adminPatientVUS
     */
    
    DefaultTableModel model;
    PersonDirectory perList;
    PatientDirectory patDirectory;
    
//    public adminPatientVUS() {
//        this(perList);
//    }

    /**
     * Creates new form adminPatientVUS
     */
    public adminPatientVUS(PersonDirectory perList, PatientDirectory patDirectory) {
        initComponents();
        this.perList = perList;
        this.patDirectory = patDirectory;
        
        populatePatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populatePatient() {
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
